version: "3"

# docker-compose.exe -f .\DockerCompose-localdev.yml up

services:
    bff:
        image: "bff-service:latest"
        build: 
          context: ../source/ui
          dockerfile: Dockerfile
        ports:
          - "5000:80"
        depends_on:
          - thing-service
          - count-service
        environment:
          - THING_HOST=thing
          - THING_PORT=5000
          - COUNT_HOST=count
          - COUNT_PORT=8080
    count:
        image: "count-service:latest"
        build: 
          context: ../source/count-service
          dockerfile: Dockerfile
        ports:
          - "5001:8080"
    thing:
        image: "thing-service:latest"
        build: 
          context: ../source/thing-service
          dockerfile: Dockerfile
        ports:
          - "5002:5000"
        depends_on:
            - db
    db:
        image: "sql-service:latest"
        build: 
          dockerfile: Dockerfile.sql-service
        ports:
          - "1433:1433"


