version: "3"

# docker-compose.exe -f .\DockerCompose-localdev.yml up

services:
    ui-service: 
        image: "ui-service:latest"
        build:
          context: ../source/ui-service
          dockerfile: Dockerfile
        ports: 
          - "8080:8000"
    bff-service:
        image: "bff-service:latest"
        build: 
          context: ../source/bff-service
          dockerfile: Dockerfile
        ports:
          - "5000:80"
    count-service:
        image: "count-service:latest"
        build: 
          context: ../source/count-service
          dockerfile: Dockerfile
        ports:
          - "5001:8080"
    thing-noauth-service:
        image: "thing-service:latest"
        build: 
          context: ../source/thing-service
          dockerfile: Dockerfile
        ports:
          - "5002:5000"
        depends_on:
            - db
    db:
        image: "sql-service:latest"
        build: 
          dockerfile: Dockerfile.sql-service
        ports:
          - "1433:1433"


