name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build-ui:

    runs-on: ubuntu-latest


    steps:    
    - uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          name/app

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into registry 
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build & Push UI
      uses: docker/build-push-action@v2
      with:
        push: true
        context:  source/ui
        tags: ui:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build & Push count service
      uses: docker/build-push-action@v2
      with:
        push: true
        context:  source/count-service
        tags: ${{ secrets.ACR_ENDPOINT }}/count-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
  
    - name: Build & Push thing service
      uses: docker/build-push-action@v2
      with:
        push: true
        context:  source/thing-service
        tags: ${{ secrets.ACR_ENDPOINT }}/thing-service:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}

  # build-subscriptions-server:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2    

  #   - name: Log into registry 
  #     uses: docker/login-action@v1 
  #     with:
  #       registry: ${{ secrets.ACR_ENDPOINT }}
  #       username: ${{ secrets.ACR_USERNAME }}
  #       password: ${{ secrets.ACR_PASSWORD }}

  #   - name: Build & Push
  #     uses: docker/build-push-action@v2
  #     with:
  #       context:  source/subscriptions_server
  #       push: true
  #       tags: adaptpaas.azurecr.io/adapt/subscriptions_server:${{ github.sha }}
  #       labels: ${{ steps.meta.outputs.labels }}

  # deploy-to-prod:
  #   runs-on: ubuntu-latest
  #   needs: [build-ui, build-subscriptions-server]

  #   steps:
  #     - name: Deploy Subscription Server
  #       id: deploy-subscriptions-server-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'adaptpaas-subscriptions-server'
  #         slot-name: 'production'
  #         publish-profile: ${{ secrets.AzureAppService_Subscriptions_Server_PublishProfile }}
  #         images: 'adaptpaas.azurecr.io/adapt/subscriptions_server:${{ github.sha }}'
      
  #     - name: Deploy UI
  #       id: deploy-ui-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'adaptpaas-client'
  #         slot-name: 'production'
  #         publish-profile: ${{ secrets.AzureAppService_UI_PublishProfile }}
  #         images: 'adaptpaas.azurecr.io/adapt/ui:${{ github.sha }}'

